name: pinksecret_front
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_modular: 6.3.1
  uno: ^1.1.9
  asp: 2.0.0
  font_awesome_flutter: ^10.8.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.1
  dynamic_color: ^1.6.6
  google_fonts: 6.0.0
  flutter_animate: ^4.5.0
  dio: ^5.7.0
  iconsax: ^0.0.8
  dio_smart_retry: ^6.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/svg/
